name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image
    # and `dev` as Docker `dev` image.
    branches:
      - master
      - dev

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

#env:
  # TODO: Change variable to your image's name.
  #IMAGE_NAME: jassa-bot

jobs:
  gitleaks:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Check for any exposed keys
      uses: zricethezav/gitleaks-action@master

  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    # If gitleaks fails stop workflow
    needs: gitleaks

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: self-hosted
    # Don't push docker image on PRs
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag jassa-bot

      - name: Log into Dockerhub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u jorgen1040 --password-stdin

      - name: Push image to Dockerhub
        run: |
          IMAGE_ID=${{ github.repository_owner }}/jassa-bot

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          [ "$VERSION" == "dev"] && VERSION=dev
 
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag jassa-bot $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION